### ISSUE TITLE
Invoke-RemoteMimikatz: EncodedCompressedFile incomplete

### ISSUE THREAD

**Issue by 0x6d69636b** [xorrior/RandomPS-Scripts#9]
Hi xorrior, 
First of all, great idea - thank you!

On line 261, the $EncodedCompressedFile seems incomplete, the encoded string is missing a terminator.

Thanks, Mick

**Comment by xorrior** [comment]
@0x6d69636b thanks for catching that

**Comment by xorrior** [comment]
Fixed. https://github.com/xorrior/RandomPS-Scripts/commit/a9321cf34618e24f66daa43451a61c917ceb7b26
